---

- name: Set MariaDB config file
  template:
    src: etc_my.cnf.j2
    owner: root
    group: root
    mode: 0644
    dest: "{{ mariadb_conf_file }}"
  notify: restart mariadb

- name: Ensure MariaDB is started
  service:
    name: mariadb
    state: started
    enabled: true
  when: not mariadb_docker
