---

- name: Include OS-specific variables.
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

- import_tasks: install.yml
  when: not mariadb_docker

- import_tasks: docker.yml
  when: mariadb_docker

- import_tasks: configure.yml

- import_tasks: secure.yml
  when: not mariadb_docker

- import_tasks: users.yml
  when: not mariadb_docker

- import_tasks: databases.yml
  when: not mariadb_docker
